language: java

# https://github.com/travis-ci/travis-ci/issues/2316#issuecomment-245829804
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3

branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.m2
  - $HOME/Library/Caches/Homebrew
